// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shipping.proto

package shipping

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateDeliveryOrderRequest struct {
	DeliveryOrder        *DeliveryOrder `protobuf:"bytes,1,opt,name=delivery_order,json=deliveryOrder,proto3" json:"delivery_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateDeliveryOrderRequest) Reset()         { *m = CreateDeliveryOrderRequest{} }
func (m *CreateDeliveryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeliveryOrderRequest) ProtoMessage()    {}
func (*CreateDeliveryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_82d3f0f2a4a861ea, []int{0}
}
func (m *CreateDeliveryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeliveryOrderRequest.Unmarshal(m, b)
}
func (m *CreateDeliveryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeliveryOrderRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDeliveryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeliveryOrderRequest.Merge(dst, src)
}
func (m *CreateDeliveryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeliveryOrderRequest.Size(m)
}
func (m *CreateDeliveryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeliveryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeliveryOrderRequest proto.InternalMessageInfo

func (m *CreateDeliveryOrderRequest) GetDeliveryOrder() *DeliveryOrder {
	if m != nil {
		return m.DeliveryOrder
	}
	return nil
}

type ListDeliveryOrdersRequest struct {
	StakeholderId        int64    `protobuf:"varint,1,opt,name=stakeholder_id,json=stakeholderId,proto3" json:"stakeholder_id,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDeliveryOrdersRequest) Reset()         { *m = ListDeliveryOrdersRequest{} }
func (m *ListDeliveryOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*ListDeliveryOrdersRequest) ProtoMessage()    {}
func (*ListDeliveryOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_82d3f0f2a4a861ea, []int{1}
}
func (m *ListDeliveryOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeliveryOrdersRequest.Unmarshal(m, b)
}
func (m *ListDeliveryOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeliveryOrdersRequest.Marshal(b, m, deterministic)
}
func (dst *ListDeliveryOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeliveryOrdersRequest.Merge(dst, src)
}
func (m *ListDeliveryOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_ListDeliveryOrdersRequest.Size(m)
}
func (m *ListDeliveryOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeliveryOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeliveryOrdersRequest proto.InternalMessageInfo

func (m *ListDeliveryOrdersRequest) GetStakeholderId() int64 {
	if m != nil {
		return m.StakeholderId
	}
	return 0
}

func (m *ListDeliveryOrdersRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *ListDeliveryOrdersRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

type ListDeliveryOrdersResponse struct {
	DeliveryOrders       []*DeliveryOrder `protobuf:"bytes,1,rep,name=delivery_orders,json=deliveryOrders,proto3" json:"delivery_orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListDeliveryOrdersResponse) Reset()         { *m = ListDeliveryOrdersResponse{} }
func (m *ListDeliveryOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*ListDeliveryOrdersResponse) ProtoMessage()    {}
func (*ListDeliveryOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_82d3f0f2a4a861ea, []int{2}
}
func (m *ListDeliveryOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeliveryOrdersResponse.Unmarshal(m, b)
}
func (m *ListDeliveryOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeliveryOrdersResponse.Marshal(b, m, deterministic)
}
func (dst *ListDeliveryOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeliveryOrdersResponse.Merge(dst, src)
}
func (m *ListDeliveryOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_ListDeliveryOrdersResponse.Size(m)
}
func (m *ListDeliveryOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeliveryOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeliveryOrdersResponse proto.InternalMessageInfo

func (m *ListDeliveryOrdersResponse) GetDeliveryOrders() []*DeliveryOrder {
	if m != nil {
		return m.DeliveryOrders
	}
	return nil
}

type UpdateDeliveryOrderRequest struct {
	DeliveryOrder        *DeliveryOrder `protobuf:"bytes,1,opt,name=delivery_order,json=deliveryOrder,proto3" json:"delivery_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateDeliveryOrderRequest) Reset()         { *m = UpdateDeliveryOrderRequest{} }
func (m *UpdateDeliveryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDeliveryOrderRequest) ProtoMessage()    {}
func (*UpdateDeliveryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_82d3f0f2a4a861ea, []int{3}
}
func (m *UpdateDeliveryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeliveryOrderRequest.Unmarshal(m, b)
}
func (m *UpdateDeliveryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeliveryOrderRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateDeliveryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeliveryOrderRequest.Merge(dst, src)
}
func (m *UpdateDeliveryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDeliveryOrderRequest.Size(m)
}
func (m *UpdateDeliveryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeliveryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeliveryOrderRequest proto.InternalMessageInfo

func (m *UpdateDeliveryOrderRequest) GetDeliveryOrder() *DeliveryOrder {
	if m != nil {
		return m.DeliveryOrder
	}
	return nil
}

type DeleteDeliveryOrderRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeliveryOrderRequest) Reset()         { *m = DeleteDeliveryOrderRequest{} }
func (m *DeleteDeliveryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeliveryOrderRequest) ProtoMessage()    {}
func (*DeleteDeliveryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_82d3f0f2a4a861ea, []int{4}
}
func (m *DeleteDeliveryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeliveryOrderRequest.Unmarshal(m, b)
}
func (m *DeleteDeliveryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeliveryOrderRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteDeliveryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeliveryOrderRequest.Merge(dst, src)
}
func (m *DeleteDeliveryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeliveryOrderRequest.Size(m)
}
func (m *DeleteDeliveryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeliveryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeliveryOrderRequest proto.InternalMessageInfo

func (m *DeleteDeliveryOrderRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeliveryOrder struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StakeholderId        int64    `protobuf:"varint,2,opt,name=stakeholder_id,json=stakeholderId,proto3" json:"stakeholder_id,omitempty"`
	Reference            string   `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	DestinationAddress   string   `protobuf:"bytes,4,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	DestinationZip       string   `protobuf:"bytes,5,opt,name=destination_zip,json=destinationZip,proto3" json:"destination_zip,omitempty"`
	DestinationLat       float64  `protobuf:"fixed64,6,opt,name=destination_lat,json=destinationLat,proto3" json:"destination_lat,omitempty"`
	DestinationLng       float64  `protobuf:"fixed64,7,opt,name=destination_lng,json=destinationLng,proto3" json:"destination_lng,omitempty"`
	TotalWeight          float64  `protobuf:"fixed64,8,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	RoutingSequence      int64    `protobuf:"varint,9,opt,name=routing_sequence,json=routingSequence,proto3" json:"routing_sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliveryOrder) Reset()         { *m = DeliveryOrder{} }
func (m *DeliveryOrder) String() string { return proto.CompactTextString(m) }
func (*DeliveryOrder) ProtoMessage()    {}
func (*DeliveryOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_82d3f0f2a4a861ea, []int{5}
}
func (m *DeliveryOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryOrder.Unmarshal(m, b)
}
func (m *DeliveryOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryOrder.Marshal(b, m, deterministic)
}
func (dst *DeliveryOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryOrder.Merge(dst, src)
}
func (m *DeliveryOrder) XXX_Size() int {
	return xxx_messageInfo_DeliveryOrder.Size(m)
}
func (m *DeliveryOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryOrder.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryOrder proto.InternalMessageInfo

func (m *DeliveryOrder) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeliveryOrder) GetStakeholderId() int64 {
	if m != nil {
		return m.StakeholderId
	}
	return 0
}

func (m *DeliveryOrder) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *DeliveryOrder) GetDestinationAddress() string {
	if m != nil {
		return m.DestinationAddress
	}
	return ""
}

func (m *DeliveryOrder) GetDestinationZip() string {
	if m != nil {
		return m.DestinationZip
	}
	return ""
}

func (m *DeliveryOrder) GetDestinationLat() float64 {
	if m != nil {
		return m.DestinationLat
	}
	return 0
}

func (m *DeliveryOrder) GetDestinationLng() float64 {
	if m != nil {
		return m.DestinationLng
	}
	return 0
}

func (m *DeliveryOrder) GetTotalWeight() float64 {
	if m != nil {
		return m.TotalWeight
	}
	return 0
}

func (m *DeliveryOrder) GetRoutingSequence() int64 {
	if m != nil {
		return m.RoutingSequence
	}
	return 0
}

type EmptyDeliveryOrder struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyDeliveryOrder) Reset()         { *m = EmptyDeliveryOrder{} }
func (m *EmptyDeliveryOrder) String() string { return proto.CompactTextString(m) }
func (*EmptyDeliveryOrder) ProtoMessage()    {}
func (*EmptyDeliveryOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_82d3f0f2a4a861ea, []int{6}
}
func (m *EmptyDeliveryOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyDeliveryOrder.Unmarshal(m, b)
}
func (m *EmptyDeliveryOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyDeliveryOrder.Marshal(b, m, deterministic)
}
func (dst *EmptyDeliveryOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyDeliveryOrder.Merge(dst, src)
}
func (m *EmptyDeliveryOrder) XXX_Size() int {
	return xxx_messageInfo_EmptyDeliveryOrder.Size(m)
}
func (m *EmptyDeliveryOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyDeliveryOrder.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyDeliveryOrder proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateDeliveryOrderRequest)(nil), "CreateDeliveryOrderRequest")
	proto.RegisterType((*ListDeliveryOrdersRequest)(nil), "ListDeliveryOrdersRequest")
	proto.RegisterType((*ListDeliveryOrdersResponse)(nil), "ListDeliveryOrdersResponse")
	proto.RegisterType((*UpdateDeliveryOrderRequest)(nil), "UpdateDeliveryOrderRequest")
	proto.RegisterType((*DeleteDeliveryOrderRequest)(nil), "DeleteDeliveryOrderRequest")
	proto.RegisterType((*DeliveryOrder)(nil), "DeliveryOrder")
	proto.RegisterType((*EmptyDeliveryOrder)(nil), "EmptyDeliveryOrder")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShippingServiceClient is the client API for ShippingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShippingServiceClient interface {
	ListDeliveryOrders(ctx context.Context, in *ListDeliveryOrdersRequest, opts ...grpc.CallOption) (*ListDeliveryOrdersResponse, error)
	CreateDeliveryOrder(ctx context.Context, in *CreateDeliveryOrderRequest, opts ...grpc.CallOption) (*DeliveryOrder, error)
	UpdateDeliveryOrder(ctx context.Context, in *UpdateDeliveryOrderRequest, opts ...grpc.CallOption) (*DeliveryOrder, error)
	DeleteDeliveryOrder(ctx context.Context, in *DeleteDeliveryOrderRequest, opts ...grpc.CallOption) (*EmptyDeliveryOrder, error)
}

type shippingServiceClient struct {
	cc *grpc.ClientConn
}

func NewShippingServiceClient(cc *grpc.ClientConn) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) ListDeliveryOrders(ctx context.Context, in *ListDeliveryOrdersRequest, opts ...grpc.CallOption) (*ListDeliveryOrdersResponse, error) {
	out := new(ListDeliveryOrdersResponse)
	err := c.cc.Invoke(ctx, "/ShippingService/ListDeliveryOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) CreateDeliveryOrder(ctx context.Context, in *CreateDeliveryOrderRequest, opts ...grpc.CallOption) (*DeliveryOrder, error) {
	out := new(DeliveryOrder)
	err := c.cc.Invoke(ctx, "/ShippingService/CreateDeliveryOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) UpdateDeliveryOrder(ctx context.Context, in *UpdateDeliveryOrderRequest, opts ...grpc.CallOption) (*DeliveryOrder, error) {
	out := new(DeliveryOrder)
	err := c.cc.Invoke(ctx, "/ShippingService/UpdateDeliveryOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) DeleteDeliveryOrder(ctx context.Context, in *DeleteDeliveryOrderRequest, opts ...grpc.CallOption) (*EmptyDeliveryOrder, error) {
	out := new(EmptyDeliveryOrder)
	err := c.cc.Invoke(ctx, "/ShippingService/DeleteDeliveryOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingServiceServer is the server API for ShippingService service.
type ShippingServiceServer interface {
	ListDeliveryOrders(context.Context, *ListDeliveryOrdersRequest) (*ListDeliveryOrdersResponse, error)
	CreateDeliveryOrder(context.Context, *CreateDeliveryOrderRequest) (*DeliveryOrder, error)
	UpdateDeliveryOrder(context.Context, *UpdateDeliveryOrderRequest) (*DeliveryOrder, error)
	DeleteDeliveryOrder(context.Context, *DeleteDeliveryOrderRequest) (*EmptyDeliveryOrder, error)
}

func RegisterShippingServiceServer(s *grpc.Server, srv ShippingServiceServer) {
	s.RegisterService(&_ShippingService_serviceDesc, srv)
}

func _ShippingService_ListDeliveryOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeliveryOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).ListDeliveryOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShippingService/ListDeliveryOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).ListDeliveryOrders(ctx, req.(*ListDeliveryOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_CreateDeliveryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeliveryOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CreateDeliveryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShippingService/CreateDeliveryOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CreateDeliveryOrder(ctx, req.(*CreateDeliveryOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_UpdateDeliveryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeliveryOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).UpdateDeliveryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShippingService/UpdateDeliveryOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).UpdateDeliveryOrder(ctx, req.(*UpdateDeliveryOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_DeleteDeliveryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeliveryOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).DeleteDeliveryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShippingService/DeleteDeliveryOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).DeleteDeliveryOrder(ctx, req.(*DeleteDeliveryOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShippingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDeliveryOrders",
			Handler:    _ShippingService_ListDeliveryOrders_Handler,
		},
		{
			MethodName: "CreateDeliveryOrder",
			Handler:    _ShippingService_CreateDeliveryOrder_Handler,
		},
		{
			MethodName: "UpdateDeliveryOrder",
			Handler:    _ShippingService_UpdateDeliveryOrder_Handler,
		},
		{
			MethodName: "DeleteDeliveryOrder",
			Handler:    _ShippingService_DeleteDeliveryOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipping.proto",
}

func init() { proto.RegisterFile("shipping.proto", fileDescriptor_shipping_82d3f0f2a4a861ea) }

var fileDescriptor_shipping_82d3f0f2a4a861ea = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xd1, 0x6a, 0x13, 0x41,
	0x14, 0x86, 0xd9, 0x8d, 0xad, 0xcd, 0x89, 0xd9, 0xc8, 0xc4, 0x8b, 0x71, 0x23, 0x18, 0x17, 0xd4,
	0x08, 0xb2, 0x42, 0x45, 0xbc, 0xb6, 0x56, 0x44, 0xa8, 0x5a, 0x12, 0x8a, 0xd0, 0x9b, 0x65, 0xda,
	0x39, 0x6e, 0x06, 0xb7, 0xb3, 0xe3, 0xcc, 0xa4, 0x52, 0x5f, 0xc1, 0xa7, 0xf1, 0x85, 0x7c, 0x16,
	0x99, 0x49, 0x6a, 0xb2, 0xd9, 0x5d, 0xaf, 0x7a, 0x99, 0xff, 0x7c, 0xf9, 0xd9, 0xf3, 0xf3, 0x9f,
	0x81, 0xc8, 0xcc, 0x85, 0x52, 0x42, 0xe6, 0xa9, 0xd2, 0xa5, 0x2d, 0x93, 0x19, 0xc4, 0x6f, 0x35,
	0x32, 0x8b, 0x87, 0x58, 0x88, 0x4b, 0xd4, 0x57, 0x9f, 0x35, 0x47, 0x3d, 0xc5, 0xef, 0x0b, 0x34,
	0x96, 0xbc, 0x82, 0x88, 0xaf, 0xf4, 0xac, 0x74, 0x03, 0x1a, 0x8c, 0x83, 0x49, 0x6f, 0x3f, 0x4a,
	0xab, 0x78, 0x9f, 0x6f, 0xfe, 0x4c, 0x7e, 0x05, 0x70, 0xff, 0x48, 0x18, 0x5b, 0x81, 0xcc, 0xb5,
	0xe9, 0x63, 0x88, 0x8c, 0x65, 0xdf, 0x70, 0x5e, 0x16, 0x1c, 0x75, 0x26, 0xb8, 0x37, 0xed, 0x4c,
	0xfb, 0x1b, 0xea, 0x07, 0x4e, 0x1e, 0x42, 0x4f, 0xb1, 0x1c, 0x33, 0xb9, 0xb8, 0x38, 0x43, 0x4d,
	0xc3, 0x71, 0x30, 0xd9, 0x99, 0x82, 0x93, 0x3e, 0x79, 0x85, 0x3c, 0x81, 0x81, 0x46, 0xb3, 0x28,
	0x6c, 0xa6, 0x50, 0x67, 0x6e, 0x40, 0x3b, 0x1e, 0xea, 0x2f, 0xe5, 0x63, 0xd4, 0xc7, 0x2c, 0xc7,
	0xe4, 0x04, 0xe2, 0xa6, 0x8f, 0x31, 0xaa, 0x94, 0x06, 0xc9, 0x6b, 0x18, 0x54, 0x57, 0x34, 0x34,
	0x18, 0x77, 0x1a, 0x76, 0x8c, 0x2a, 0x3b, 0x1a, 0x97, 0xdc, 0x89, 0xe2, 0x37, 0x9c, 0xdc, 0x73,
	0x88, 0x0f, 0xb1, 0xc0, 0x16, 0xd3, 0x08, 0xc2, 0x7f, 0x69, 0x85, 0x82, 0x27, 0x7f, 0x42, 0xe8,
	0x57, 0xc0, 0x6d, 0xa2, 0x21, 0xeb, 0xb0, 0x29, 0xeb, 0x07, 0xd0, 0xd5, 0xf8, 0x15, 0x35, 0xca,
	0xf3, 0x65, 0x88, 0xdd, 0xe9, 0x5a, 0x20, 0x2f, 0x60, 0xc8, 0xd1, 0x58, 0x21, 0x99, 0x15, 0xa5,
	0xcc, 0x18, 0xe7, 0x1a, 0x8d, 0xa1, 0xb7, 0x3c, 0x47, 0x36, 0x46, 0x6f, 0x96, 0x13, 0xf2, 0xd4,
	0x65, 0xba, 0xfe, 0xc3, 0x4f, 0xa1, 0xe8, 0x8e, 0x87, 0xa3, 0x0d, 0xf9, 0x54, 0xa8, 0x6d, 0xb0,
	0x60, 0x96, 0xee, 0x8e, 0x83, 0x49, 0x50, 0x01, 0x8f, 0x98, 0xad, 0x81, 0x32, 0xa7, 0xb7, 0xeb,
	0xa0, 0xcc, 0xc9, 0x23, 0xb8, 0x63, 0x4b, 0xcb, 0x8a, 0xec, 0x07, 0x8a, 0x7c, 0x6e, 0xe9, 0x9e,
	0xa7, 0x7a, 0x5e, 0xfb, 0xe2, 0x25, 0xf2, 0x0c, 0xee, 0xea, 0x72, 0x61, 0x85, 0xcc, 0x33, 0xe3,
	0x82, 0x75, 0x3b, 0x77, 0x7d, 0x2a, 0x83, 0x95, 0x3e, 0x5b, 0xc9, 0xc9, 0x3d, 0x20, 0xef, 0x2e,
	0x94, 0xbd, 0xaa, 0x84, 0xbc, 0xff, 0x3b, 0x84, 0xc1, 0x6c, 0x75, 0x46, 0x33, 0xd4, 0x97, 0xe2,
	0x1c, 0xc9, 0x47, 0x20, 0xf5, 0x92, 0x91, 0x38, 0x6d, 0x3d, 0x83, 0x78, 0x94, 0xfe, 0xa7, 0x95,
	0x07, 0x30, 0x6c, 0x38, 0x4b, 0x32, 0x4a, 0xdb, 0x8f, 0x35, 0xde, 0xaa, 0x96, 0xf3, 0x68, 0x28,
	0x28, 0x19, 0xa5, 0xed, 0xb5, 0xad, 0x79, 0xbc, 0x87, 0x61, 0x43, 0x1f, 0xc9, 0x28, 0x6d, 0x6f,
	0x69, 0x3c, 0x4c, 0xeb, 0x99, 0x1d, 0xc0, 0xe9, 0xde, 0xf5, 0xcb, 0x73, 0xb6, 0xeb, 0x9f, 0x9e,
	0x97, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x62, 0x05, 0x11, 0x8c, 0x04, 0x00, 0x00,
}
