// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shipping.proto

package shipping

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListDeliveryOrdersRequest struct {
	StakeholderId        int64    `protobuf:"varint,1,opt,name=stakeholder_id,json=stakeholderId,proto3" json:"stakeholder_id,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDeliveryOrdersRequest) Reset()         { *m = ListDeliveryOrdersRequest{} }
func (m *ListDeliveryOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*ListDeliveryOrdersRequest) ProtoMessage()    {}
func (*ListDeliveryOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_15e294e50fbb529d, []int{0}
}
func (m *ListDeliveryOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeliveryOrdersRequest.Unmarshal(m, b)
}
func (m *ListDeliveryOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeliveryOrdersRequest.Marshal(b, m, deterministic)
}
func (dst *ListDeliveryOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeliveryOrdersRequest.Merge(dst, src)
}
func (m *ListDeliveryOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_ListDeliveryOrdersRequest.Size(m)
}
func (m *ListDeliveryOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeliveryOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeliveryOrdersRequest proto.InternalMessageInfo

func (m *ListDeliveryOrdersRequest) GetStakeholderId() int64 {
	if m != nil {
		return m.StakeholderId
	}
	return 0
}

func (m *ListDeliveryOrdersRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *ListDeliveryOrdersRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

type ListDeliveryOrdersResponse struct {
	DeliveryOrders       []*DeliveryOrder `protobuf:"bytes,1,rep,name=delivery_orders,json=deliveryOrders,proto3" json:"delivery_orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListDeliveryOrdersResponse) Reset()         { *m = ListDeliveryOrdersResponse{} }
func (m *ListDeliveryOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*ListDeliveryOrdersResponse) ProtoMessage()    {}
func (*ListDeliveryOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_15e294e50fbb529d, []int{1}
}
func (m *ListDeliveryOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeliveryOrdersResponse.Unmarshal(m, b)
}
func (m *ListDeliveryOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeliveryOrdersResponse.Marshal(b, m, deterministic)
}
func (dst *ListDeliveryOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeliveryOrdersResponse.Merge(dst, src)
}
func (m *ListDeliveryOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_ListDeliveryOrdersResponse.Size(m)
}
func (m *ListDeliveryOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeliveryOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeliveryOrdersResponse proto.InternalMessageInfo

func (m *ListDeliveryOrdersResponse) GetDeliveryOrders() []*DeliveryOrder {
	if m != nil {
		return m.DeliveryOrders
	}
	return nil
}

type DeliveryOrder struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StakeholderId        int64    `protobuf:"varint,2,opt,name=stakeholder_id,json=stakeholderId,proto3" json:"stakeholder_id,omitempty"`
	Reference            string   `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	DestinationAddress   string   `protobuf:"bytes,4,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	DestinationZip       string   `protobuf:"bytes,5,opt,name=destination_zip,json=destinationZip,proto3" json:"destination_zip,omitempty"`
	DestinationLat       float32  `protobuf:"fixed32,6,opt,name=destination_lat,json=destinationLat,proto3" json:"destination_lat,omitempty"`
	DestinationLng       float32  `protobuf:"fixed32,7,opt,name=destination_lng,json=destinationLng,proto3" json:"destination_lng,omitempty"`
	TotalWeight          float32  `protobuf:"fixed32,8,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	RoutingSequence      int64    `protobuf:"varint,9,opt,name=routing_sequence,json=routingSequence,proto3" json:"routing_sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliveryOrder) Reset()         { *m = DeliveryOrder{} }
func (m *DeliveryOrder) String() string { return proto.CompactTextString(m) }
func (*DeliveryOrder) ProtoMessage()    {}
func (*DeliveryOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_15e294e50fbb529d, []int{2}
}
func (m *DeliveryOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryOrder.Unmarshal(m, b)
}
func (m *DeliveryOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryOrder.Marshal(b, m, deterministic)
}
func (dst *DeliveryOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryOrder.Merge(dst, src)
}
func (m *DeliveryOrder) XXX_Size() int {
	return xxx_messageInfo_DeliveryOrder.Size(m)
}
func (m *DeliveryOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryOrder.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryOrder proto.InternalMessageInfo

func (m *DeliveryOrder) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeliveryOrder) GetStakeholderId() int64 {
	if m != nil {
		return m.StakeholderId
	}
	return 0
}

func (m *DeliveryOrder) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *DeliveryOrder) GetDestinationAddress() string {
	if m != nil {
		return m.DestinationAddress
	}
	return ""
}

func (m *DeliveryOrder) GetDestinationZip() string {
	if m != nil {
		return m.DestinationZip
	}
	return ""
}

func (m *DeliveryOrder) GetDestinationLat() float32 {
	if m != nil {
		return m.DestinationLat
	}
	return 0
}

func (m *DeliveryOrder) GetDestinationLng() float32 {
	if m != nil {
		return m.DestinationLng
	}
	return 0
}

func (m *DeliveryOrder) GetTotalWeight() float32 {
	if m != nil {
		return m.TotalWeight
	}
	return 0
}

func (m *DeliveryOrder) GetRoutingSequence() int64 {
	if m != nil {
		return m.RoutingSequence
	}
	return 0
}

func init() {
	proto.RegisterType((*ListDeliveryOrdersRequest)(nil), "ListDeliveryOrdersRequest")
	proto.RegisterType((*ListDeliveryOrdersResponse)(nil), "ListDeliveryOrdersResponse")
	proto.RegisterType((*DeliveryOrder)(nil), "DeliveryOrder")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShippingServiceClient is the client API for ShippingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShippingServiceClient interface {
	ListDeliveryOrders(ctx context.Context, in *ListDeliveryOrdersRequest, opts ...grpc.CallOption) (*ListDeliveryOrdersResponse, error)
}

type shippingServiceClient struct {
	cc *grpc.ClientConn
}

func NewShippingServiceClient(cc *grpc.ClientConn) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) ListDeliveryOrders(ctx context.Context, in *ListDeliveryOrdersRequest, opts ...grpc.CallOption) (*ListDeliveryOrdersResponse, error) {
	out := new(ListDeliveryOrdersResponse)
	err := c.cc.Invoke(ctx, "/ShippingService/ListDeliveryOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingServiceServer is the server API for ShippingService service.
type ShippingServiceServer interface {
	ListDeliveryOrders(context.Context, *ListDeliveryOrdersRequest) (*ListDeliveryOrdersResponse, error)
}

func RegisterShippingServiceServer(s *grpc.Server, srv ShippingServiceServer) {
	s.RegisterService(&_ShippingService_serviceDesc, srv)
}

func _ShippingService_ListDeliveryOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeliveryOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).ListDeliveryOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShippingService/ListDeliveryOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).ListDeliveryOrders(ctx, req.(*ListDeliveryOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShippingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDeliveryOrders",
			Handler:    _ShippingService_ListDeliveryOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipping.proto",
}

func init() { proto.RegisterFile("shipping.proto", fileDescriptor_shipping_15e294e50fbb529d) }

var fileDescriptor_shipping_15e294e50fbb529d = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x8e, 0xd3, 0x30,
	0x14, 0x45, 0x95, 0x94, 0x19, 0xa6, 0xaf, 0x34, 0x41, 0x66, 0x63, 0x0a, 0x12, 0xa1, 0x12, 0x10,
	0x36, 0x41, 0x1a, 0x16, 0xac, 0x41, 0x6c, 0x90, 0x0a, 0x54, 0xa9, 0x10, 0x52, 0x37, 0xc6, 0xad,
	0x1f, 0xa9, 0x45, 0xb0, 0x8d, 0xed, 0x14, 0xc1, 0x2f, 0xf0, 0x8f, 0x7c, 0x0b, 0x8a, 0x1b, 0x68,
	0x43, 0xdb, 0xed, 0xb9, 0xc7, 0x51, 0xae, 0x7d, 0x21, 0x71, 0x1b, 0x69, 0x8c, 0x54, 0x55, 0x61,
	0xac, 0xf6, 0x7a, 0xfa, 0x2b, 0x82, 0xbb, 0x33, 0xe9, 0xfc, 0x6b, 0xac, 0xe5, 0x16, 0xed, 0x8f,
	0xf7, 0x56, 0xa0, 0x75, 0x25, 0x7e, 0x6b, 0xd0, 0x79, 0xf2, 0x08, 0x12, 0xe7, 0xf9, 0x17, 0xdc,
	0xe8, 0x5a, 0xa0, 0x65, 0x52, 0xd0, 0x28, 0x8b, 0xf2, 0x41, 0x39, 0x3e, 0xa0, 0x6f, 0x04, 0x79,
	0x00, 0x23, 0xc3, 0x2b, 0x64, 0xaa, 0xf9, 0xba, 0x42, 0x4b, 0xe3, 0x2c, 0xca, 0x2f, 0x4a, 0x68,
	0xd1, 0xbb, 0x40, 0xc8, 0x63, 0x48, 0x2d, 0xba, 0xa6, 0xf6, 0xcc, 0xa0, 0x65, 0x6d, 0x40, 0x07,
	0x41, 0x1a, 0xef, 0xf0, 0x1c, 0xed, 0x9c, 0x57, 0x38, 0xfd, 0x00, 0x93, 0x53, 0x3f, 0xe3, 0x8c,
	0x56, 0x0e, 0xc9, 0x0b, 0x48, 0x45, 0x97, 0x30, 0x1d, 0x22, 0x1a, 0x65, 0x83, 0x7c, 0x74, 0x9d,
	0x14, 0xbd, 0x13, 0x65, 0x22, 0x7a, 0x1f, 0x98, 0xfe, 0x8e, 0x61, 0xdc, 0x33, 0x48, 0x02, 0xf1,
	0xbf, 0x32, 0xb1, 0x14, 0x27, 0x8a, 0xc6, 0xa7, 0x8a, 0xde, 0x87, 0xa1, 0xc5, 0xcf, 0x68, 0x51,
	0xad, 0x77, 0x0d, 0x86, 0xe5, 0x1e, 0x90, 0x67, 0x70, 0x47, 0xa0, 0xf3, 0x52, 0x71, 0x2f, 0xb5,
	0x62, 0x5c, 0x08, 0x8b, 0xce, 0xd1, 0x1b, 0xc1, 0x23, 0x07, 0xd1, 0xcb, 0x5d, 0x42, 0x9e, 0xb4,
	0x85, 0xf6, 0x07, 0x7e, 0x4a, 0x43, 0x2f, 0x82, 0x9c, 0x1c, 0xe0, 0xa5, 0x34, 0xff, 0x8b, 0x35,
	0xf7, 0xf4, 0x32, 0x8b, 0xf2, 0xb8, 0x27, 0xce, 0xb8, 0x3f, 0x12, 0x55, 0x45, 0x6f, 0x1e, 0x8b,
	0xaa, 0x22, 0x0f, 0xe1, 0x96, 0xd7, 0x9e, 0xd7, 0xec, 0x3b, 0xca, 0x6a, 0xe3, 0xe9, 0x55, 0xb0,
	0x46, 0x81, 0x7d, 0x0c, 0x88, 0x3c, 0x85, 0xdb, 0x56, 0x37, 0x5e, 0xaa, 0x8a, 0xb9, 0x76, 0x0f,
	0x6d, 0xe7, 0x61, 0xb8, 0x95, 0xb4, 0xe3, 0x8b, 0x0e, 0x5f, 0x7f, 0x82, 0x74, 0xd1, 0xed, 0x6a,
	0x81, 0x76, 0x2b, 0xd7, 0x48, 0xde, 0x02, 0x39, 0x7e, 0x4a, 0x32, 0x29, 0xce, 0x8e, 0x6d, 0x72,
	0xaf, 0x38, 0xff, 0xf6, 0xaf, 0x60, 0x79, 0xf5, 0x77, 0xb9, 0xab, 0xcb, 0x30, 0xdd, 0xe7, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x95, 0x08, 0x02, 0x55, 0xcc, 0x02, 0x00, 0x00,
}
