// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metric.proto

package metric

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_metric_8339e2d44616d591, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CreatePageViewRequest struct {
	PageView             *PageView `protobuf:"bytes,1,opt,name=page_view,json=pageView,proto3" json:"page_view,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatePageViewRequest) Reset()         { *m = CreatePageViewRequest{} }
func (m *CreatePageViewRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePageViewRequest) ProtoMessage()    {}
func (*CreatePageViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metric_8339e2d44616d591, []int{1}
}
func (m *CreatePageViewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePageViewRequest.Unmarshal(m, b)
}
func (m *CreatePageViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePageViewRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePageViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePageViewRequest.Merge(dst, src)
}
func (m *CreatePageViewRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePageViewRequest.Size(m)
}
func (m *CreatePageViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePageViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePageViewRequest proto.InternalMessageInfo

func (m *CreatePageViewRequest) GetPageView() *PageView {
	if m != nil {
		return m.PageView
	}
	return nil
}

type PageView struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XForwardedHost       string   `protobuf:"bytes,2,opt,name=x_forwarded_host,json=xForwardedHost,proto3" json:"x_forwarded_host,omitempty"`
	XForwardedServer     string   `protobuf:"bytes,3,opt,name=x_forwarded_server,json=xForwardedServer,proto3" json:"x_forwarded_server,omitempty"`
	UserAgent            string   `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	XForwardedFor        string   `protobuf:"bytes,5,opt,name=x_forwarded_for,json=xForwardedFor,proto3" json:"x_forwarded_for,omitempty"`
	RequestTime          string   `protobuf:"bytes,6,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	RequestHeaders       string   `protobuf:"bytes,7,opt,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageView) Reset()         { *m = PageView{} }
func (m *PageView) String() string { return proto.CompactTextString(m) }
func (*PageView) ProtoMessage()    {}
func (*PageView) Descriptor() ([]byte, []int) {
	return fileDescriptor_metric_8339e2d44616d591, []int{2}
}
func (m *PageView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageView.Unmarshal(m, b)
}
func (m *PageView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageView.Marshal(b, m, deterministic)
}
func (dst *PageView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageView.Merge(dst, src)
}
func (m *PageView) XXX_Size() int {
	return xxx_messageInfo_PageView.Size(m)
}
func (m *PageView) XXX_DiscardUnknown() {
	xxx_messageInfo_PageView.DiscardUnknown(m)
}

var xxx_messageInfo_PageView proto.InternalMessageInfo

func (m *PageView) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PageView) GetXForwardedHost() string {
	if m != nil {
		return m.XForwardedHost
	}
	return ""
}

func (m *PageView) GetXForwardedServer() string {
	if m != nil {
		return m.XForwardedServer
	}
	return ""
}

func (m *PageView) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *PageView) GetXForwardedFor() string {
	if m != nil {
		return m.XForwardedFor
	}
	return ""
}

func (m *PageView) GetRequestTime() string {
	if m != nil {
		return m.RequestTime
	}
	return ""
}

func (m *PageView) GetRequestHeaders() string {
	if m != nil {
		return m.RequestHeaders
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*CreatePageViewRequest)(nil), "CreatePageViewRequest")
	proto.RegisterType((*PageView)(nil), "PageView")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetricClient is the client API for Metric service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetricClient interface {
	CreatePageView(ctx context.Context, in *CreatePageViewRequest, opts ...grpc.CallOption) (*Empty, error)
}

type metricClient struct {
	cc *grpc.ClientConn
}

func NewMetricClient(cc *grpc.ClientConn) MetricClient {
	return &metricClient{cc}
}

func (c *metricClient) CreatePageView(ctx context.Context, in *CreatePageViewRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Metric/CreatePageView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricServer is the server API for Metric service.
type MetricServer interface {
	CreatePageView(context.Context, *CreatePageViewRequest) (*Empty, error)
}

func RegisterMetricServer(s *grpc.Server, srv MetricServer) {
	s.RegisterService(&_Metric_serviceDesc, srv)
}

func _Metric_CreatePageView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePageViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServer).CreatePageView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Metric/CreatePageView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServer).CreatePageView(ctx, req.(*CreatePageViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metric_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Metric",
	HandlerType: (*MetricServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePageView",
			Handler:    _Metric_CreatePageView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metric.proto",
}

func init() { proto.RegisterFile("metric.proto", fileDescriptor_metric_8339e2d44616d591) }

var fileDescriptor_metric_8339e2d44616d591 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0x69, 0xfa, 0x35, 0x6d, 0xa6, 0xfd, 0xd2, 0xb2, 0xa0, 0x2c, 0x82, 0x50, 0x73, 0xa8,
	0x39, 0x48, 0x90, 0x7a, 0xf3, 0x22, 0x2a, 0x96, 0x5e, 0x04, 0x89, 0xe2, 0xc1, 0x4b, 0x58, 0xcd,
	0x34, 0xdd, 0x43, 0xdc, 0x38, 0xbb, 0x6d, 0xea, 0x0f, 0xf0, 0x7f, 0x4b, 0x37, 0x89, 0xad, 0xe0,
	0x6d, 0x78, 0x78, 0x18, 0x78, 0xdf, 0x17, 0x06, 0x39, 0x1a, 0x92, 0x6f, 0x51, 0x41, 0xca, 0xa8,
	0xa0, 0x0b, 0x9d, 0xbb, 0xbc, 0x30, 0x9f, 0xc1, 0x15, 0x1c, 0xdc, 0x12, 0x0a, 0x83, 0x0f, 0x22,
	0xc3, 0x67, 0x89, 0x65, 0x8c, 0x1f, 0x2b, 0xd4, 0x86, 0x4d, 0xc0, 0x2b, 0x44, 0x86, 0xc9, 0x5a,
	0x62, 0xc9, 0x5b, 0xe3, 0x56, 0xd8, 0x9f, 0x7a, 0xd1, 0x8f, 0xd4, 0x2b, 0xea, 0x2b, 0xf8, 0x72,
	0xa0, 0xd7, 0x60, 0xe6, 0x83, 0x23, 0x53, 0x6b, 0xb7, 0x63, 0x47, 0xa6, 0x2c, 0x84, 0xd1, 0x26,
	0x59, 0x28, 0x2a, 0x05, 0xa5, 0x98, 0x26, 0x4b, 0xa5, 0x0d, 0x77, 0xc6, 0xad, 0xd0, 0x8b, 0xfd,
	0xcd, 0xac, 0xc1, 0x73, 0xa5, 0x0d, 0x3b, 0x03, 0xb6, 0x6f, 0x6a, 0xa4, 0x35, 0x12, 0x6f, 0x5b,
	0x77, 0xb4, 0x73, 0x1f, 0x2d, 0x67, 0xc7, 0x00, 0x2b, 0x8d, 0x94, 0x88, 0x0c, 0xdf, 0x0d, 0xff,
	0x67, 0x2d, 0x6f, 0x4b, 0xae, 0xb7, 0x80, 0x4d, 0x60, 0xb8, 0xff, 0x6c, 0xa1, 0x88, 0x77, 0xac,
	0xf3, 0x7f, 0xf7, 0x69, 0xa6, 0x88, 0x9d, 0xc0, 0x80, 0xaa, 0xb8, 0x89, 0x91, 0x39, 0x72, 0xd7,
	0x4a, 0xfd, 0x9a, 0x3d, 0xc9, 0x1c, 0xd9, 0x29, 0x0c, 0x1b, 0x65, 0x89, 0x22, 0x45, 0xd2, 0xbc,
	0x5b, 0x05, 0xa8, 0xf1, 0xbc, 0xa2, 0xd3, 0x4b, 0x70, 0xef, 0x6d, 0xc3, 0xec, 0x1c, 0xfc, 0xdf,
	0x95, 0xb2, 0xc3, 0xe8, 0xcf, 0x8e, 0x8f, 0xdc, 0xc8, 0x8e, 0x70, 0xd3, 0x7b, 0x71, 0xab, 0x75,
	0x5e, 0x5d, 0x3b, 0xcf, 0xc5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xea, 0x45, 0x85, 0xae,
	0x01, 0x00, 0x00,
}
