// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer.proto

package oswee_crm_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetCustomerRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerRequest) Reset()         { *m = GetCustomerRequest{} }
func (m *GetCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomerRequest) ProtoMessage()    {}
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_9b319ef06673172a, []int{0}
}
func (m *GetCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerRequest.Unmarshal(m, b)
}
func (m *GetCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerRequest.Marshal(b, m, deterministic)
}
func (dst *GetCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerRequest.Merge(dst, src)
}
func (m *GetCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomerRequest.Size(m)
}
func (m *GetCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerRequest proto.InternalMessageInfo

func (m *GetCustomerRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetCustomerResponse struct {
	Customers            []*Customer `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetCustomerResponse) Reset()         { *m = GetCustomerResponse{} }
func (m *GetCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*GetCustomerResponse) ProtoMessage()    {}
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_9b319ef06673172a, []int{1}
}
func (m *GetCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerResponse.Unmarshal(m, b)
}
func (m *GetCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerResponse.Marshal(b, m, deterministic)
}
func (dst *GetCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerResponse.Merge(dst, src)
}
func (m *GetCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_GetCustomerResponse.Size(m)
}
func (m *GetCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerResponse proto.InternalMessageInfo

func (m *GetCustomerResponse) GetCustomers() []*Customer {
	if m != nil {
		return m.Customers
	}
	return nil
}

type Customer struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           string   `protobuf:"bytes,15,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_9b319ef06673172a, []int{2}
}
func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (dst *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(dst, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Customer) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*GetCustomerRequest)(nil), "oswee.crm.v1.GetCustomerRequest")
	proto.RegisterType((*GetCustomerResponse)(nil), "oswee.crm.v1.GetCustomerResponse")
	proto.RegisterType((*Customer)(nil), "oswee.crm.v1.Customer")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomersClient is the client API for Customers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomersClient interface {
	GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*GetCustomerResponse, error)
}

type customersClient struct {
	cc *grpc.ClientConn
}

func NewCustomersClient(cc *grpc.ClientConn) CustomersClient {
	return &customersClient{cc}
}

func (c *customersClient) GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*GetCustomerResponse, error) {
	out := new(GetCustomerResponse)
	err := c.cc.Invoke(ctx, "/oswee.crm.v1.Customers/GetCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomersServer is the server API for Customers service.
type CustomersServer interface {
	GetCustomer(context.Context, *GetCustomerRequest) (*GetCustomerResponse, error)
}

func RegisterCustomersServer(s *grpc.Server, srv CustomersServer) {
	s.RegisterService(&_Customers_serviceDesc, srv)
}

func _Customers_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.crm.v1.Customers/GetCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).GetCustomer(ctx, req.(*GetCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Customers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oswee.crm.v1.Customers",
	HandlerType: (*CustomersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomer",
			Handler:    _Customers_GetCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer.proto",
}

func init() { proto.RegisterFile("customer.proto", fileDescriptor_customer_9b319ef06673172a) }

var fileDescriptor_customer_9b319ef06673172a = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2e, 0x2d, 0x2e,
	0xc9, 0xcf, 0x4d, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc9, 0x2f, 0x2e, 0x4f,
	0x4d, 0xd5, 0x4b, 0x2e, 0xca, 0xd5, 0x2b, 0x33, 0x54, 0x52, 0xe1, 0x12, 0x72, 0x4f, 0x2d, 0x71,
	0x86, 0x2a, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0xca, 0x4c, 0x51, 0xf2, 0xe6, 0x12, 0x46, 0x51, 0x55,
	0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x64, 0xc2, 0xc5, 0x09, 0x33, 0xbc, 0x58, 0x82, 0x51, 0x81,
	0x59, 0x83, 0xdb, 0x48, 0x4c, 0x0f, 0xd9, 0x78, 0x3d, 0xb8, 0x16, 0x84, 0x42, 0x25, 0x7f, 0x2e,
	0x0e, 0x98, 0x30, 0xba, 0x45, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x3c, 0x17, 0x77, 0x72, 0x51, 0x6a, 0x62, 0x49, 0x6a,
	0x7c, 0x49, 0x66, 0x6e, 0xaa, 0x04, 0x3f, 0x58, 0x8a, 0x0b, 0x22, 0x14, 0x92, 0x99, 0x9b, 0x6a,
	0x14, 0xcf, 0xc5, 0x09, 0x33, 0xb0, 0x58, 0x28, 0x88, 0x8b, 0x1b, 0xc9, 0xa9, 0x42, 0x0a, 0xa8,
	0xee, 0xc1, 0xf4, 0xab, 0x94, 0x22, 0x1e, 0x15, 0x10, 0x7f, 0x26, 0xb1, 0x81, 0x43, 0xce, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x4d, 0xaa, 0x5f, 0x4b, 0x01, 0x00, 0x00,
}
